# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# Config version for compatibility and deprecations
config-version = 2

# You can use it to add commands that run after AeroSpace startup.
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layouts
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# macOS hidden app behavior
automatically-unhide-macos-hidden-apps = false

# Persistent workspaces
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B",
                         "C", "D", "E", "F", "G", "I", "M", "N", "O", "P", "Q",
                         "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

# Callback for binding mode changes
on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        20
    outer.right =      20

[mode.main.binding]

    alt-f = 'fullscreen'

    # Layout
    alt-q = 'layout tiles horizontal vertical'
    alt-e = 'layout accordion horizontal vertical'

    # Focus
    alt-a = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-s = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-w = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-d = 'focus --boundaries-action wrap-around-the-workspace right'

    # Move windows
    alt-shift-a = 'move left'
    alt-shift-s = 'move down'
    alt-shift-w = 'move up'
    alt-shift-d = 'move right'

    # Resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Workspaces
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-b = 'workspace B'
    alt-c = 'workspace C'

    # E is reserved for one-handed layout switching.

    alt-g = 'mode service'
    alt-i = 'workspace I'
    alt-m = 'workspace M'
    alt-n = 'workspace N'
    alt-o = 'workspace O'
    alt-p = 'workspace P'

    # Q is reserved for one-handed layout switching.

    # Disabled so League of Legends can use Option + R for self-cast
    # alt-r = 'workspace R'

    alt-t = 'workspace T'
    alt-u = 'workspace U'
    alt-v = 'workspace V'

    # W/A/S/D are reserved for one-handed window focus.

    alt-x = 'resize smart +50'
    alt-y = 'workspace Y'
    alt-z = 'resize smart -50'

    # Move window to workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    alt-shift-b = 'move-node-to-workspace B'
    alt-shift-c = 'move-node-to-workspace C'
    alt-shift-e = 'move-node-to-workspace E'
    alt-shift-i = 'move-node-to-workspace I'
    alt-shift-m = 'move-node-to-workspace M'
    alt-shift-n = 'move-node-to-workspace N'
    alt-shift-o = 'move-node-to-workspace O'
    alt-shift-p = 'move-node-to-workspace P'
    alt-shift-q = 'move-node-to-workspace Q'
    alt-shift-r = 'move-node-to-workspace R'
    alt-shift-t = 'move-node-to-workspace T'
    alt-shift-u = 'move-node-to-workspace U'
    alt-shift-v = 'move-node-to-workspace V'
    alt-shift-x = 'move-node-to-workspace X'
    alt-shift-y = 'move-node-to-workspace Y'
    alt-shift-z = 'move-node-to-workspace Z'

    # Workspace back and forth
    alt-tab = 'workspace-back-and-forth'

    # Move workspace to monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    x = ['close-all-windows-but-current', 'mode main']

    a = ['join-with left', 'mode main']
    s = ['join-with down', 'mode main']
    w = ['join-with up', 'mode main']
    d = ['join-with right', 'mode main']

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = 'move-node-to-workspace C'

[[on-window-detected]]
    if.app-id = 'com.apple.MobileSMS'
    run = 'move-node-to-workspace C'

[[on-window-detected]]
    if.app-id = 'net.whatsapp.WhatsApp'
    run = 'move-node-to-workspace C'

[[on-window-detected]]
    if.app-id = 'im.riot.app'
    run = 'move-node-to-workspace C'

[[on-window-detected]]
    if.app-id = 'com.hnc.Discord'
    run = 'move-node-to-workspace C'
