model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"
approvals_reviewer = "user"
service_tier = "default"
[projects."/Users/emilio/.config/nix-config"]
trust_level = "trusted"

[projects."/Users/emilio/.ssh"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/CheckThePrice/checktheprice-extension"]
trust_level = "trusted"

[projects."/opt/homebrew/Library/Taps/emilioak/homebrew-tap"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/LegalPal/legalpal_frontend"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/LegalPal/legalpal_backend"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis/AgentWorkflows"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis/MergeSort"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/Trading"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis"]
trust_level = "trusted"

[projects."/Users/emilio"]
trust_level = "trusted"

[projects."/Users/emilio/Downloads"]
trust_level = "trusted"

[projects."/Users/emilio/Projects/Running"]
trust_level = "trusted"

[projects."/Users/emilio/Library/Developer/Xcode/CodingAssistant/codex"]
trust_level = "trusted"

[projects."/Users/emilio/Projects/Indoor 5K"]
trust_level = "trusted"

[projects."/home/emilio/.config/nix-config"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[notice]
hide_full_access_warning = true
fast_default_opt_out = true

[features]
hooks = true

[hooks.state]

[hooks.state."/home/emilio/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:f77ba403a9658bc540fffa73346ee929294cd8e47217a8bd7c2418b5e80deaf0"
enabled = true
