#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.6-sol"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"
approvals_reviewer = "user"
service_tier = "default"
notify = ["/Users/emilio/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
personality = "pragmatic"

[projects."/Users/emilio/.config/nix-config"]
trust_level = "trusted"

[projects."/Users/emilio/.ssh"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/CheckThePrice/checktheprice-extension"]
trust_level = "trusted"

[projects."/opt/homebrew/Library/Taps/emilioak/homebrew-tap"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/LegalPal/legalpal_frontend"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/LegalPal/legalpal_backend"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis/AgentWorkflows"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis/MergeSort"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Capisoft/Trading"]
trust_level = "trusted"

[projects."/Users/emilio/Work/Thesis"]
trust_level = "trusted"

[projects."/Users/emilio"]
trust_level = "trusted"

[projects."/Users/emilio/Downloads"]
trust_level = "trusted"

[projects."/Users/emilio/Projects/Running"]
trust_level = "trusted"

[projects."/Users/emilio/Library/Developer/Xcode/CodingAssistant/codex"]
trust_level = "trusted"

[projects."/Users/emilio/Projects/Indoor 5K"]
trust_level = "trusted"

[projects."/home/emilio/.config/nix-config"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-10/when"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-10/the"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-10/i"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-10/create-a-scheduled-task-called-weekday"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-10/is"]
trust_level = "trusted"

[projects."/home/emilio"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/if"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/computer-plugin-computer-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/create-a-scheduled-task-called-weekday"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/oka"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/d"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/alr"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/linear-plugin-linear-openai-curated-remote"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/ca"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/can"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/hatch-pet-users-emilio-config-nix"]
trust_level = "trusted"

[projects."/Users/emilio/Documents/Codex/2026-07-12/hatch-pet-users-emilio-config-nix-2"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[notice]
hide_full_access_warning = true
fast_default_opt_out = true

[features]
hooks = true
js_repl = false
memories = true

[hooks.state]

[hooks.state."/home/emilio/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:f77ba403a9658bc540fffa73346ee929294cd8e47217a8bd7c2418b5e80deaf0"
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-07-12T13:41:09Z"
source_type = "local"
source = "/Users/emilio/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-10T19:05:48Z"
source_type = "local"
source = "/Users/emilio/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/emilio/.codex"
CODEX_HOME = "/Users/emilio/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,e74b67ab909392b37f7aef14977fce7aa80cfa02ade5491f30abcdbcb9e69f33"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.51957"
SKY_CUA_SERVICE_PATH = "/Users/emilio/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000387/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
followUpQueueMode = "steer"
show-context-window-usage = true
selected-avatar-id = "codex"
avatar-overlay-mascot-width-px = 80
notifications-turn-mode = "always"
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "ultra", "max"]
show-ultra-in-model-picker-slider = true
computerUseAlwaysHidePictureInPicture = true
hotkey-window-projectless-default-enabled = false
usePointerCursors = true
appearanceTheme = "dark"
preventSleepWhileRunning = false

[desktop.appearanceLightChromeTheme]
accent = "#339cff"
contrast = 45
ink = "#1a1c1f"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = "JetBrainsMono Nerd Font"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#ba2623"
skill = "#924ff7"

[desktop.appearanceDarkChromeTheme]
accent = "#339cff"
contrast = 60
ink = "#ffffff"
opaqueWindows = false
surface = "#181818"

[desktop.appearanceDarkChromeTheme.fonts]
code = "JetBrainsMono Nerd Font"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#40c977"
diffRemoved = "#fa423e"
skill = "#ad7bf9"

[memories]
generate_memories = true
use_memories = true
